[WIP ]Adds gas savings page
ethereum-optimism/frontends pull request #10
Opened 2021-04-14 17:02 UTC by gigamesh

**Description**
A clear and concise description of the features you're adding in this pull request.

**Additional context**
Add any other context about the problem you're solving.

**Metadata**
- Fixes #[Link to Issue]

2021-04-20 06:58 UTC, K-Ho approved these changes
lgtm!

2021-04-20 06:58 UTC, K-Ho commented on packages/optimism.io/src/components/GasCalcSection/index.js
> +        2000 + //20k SSTORE for a batch of 10 transctions
should be updated to be + 2600 + (executionGasPrice * L1gasUsed * 5) where executionGasPrice is 0, but customizable via the slider (see https://github.com/ethereum-optimism/frontends/issues/24). For info on the 2600 see https://www.notion.so/optimismpbc/Tx-Fee-Savings-1ac93a98d48b4178b71bd1293ec2e420

2021-04-20 06:58 UTC, K-Ho commented on packages/optimism.io/src/components/GasCalcSection/index.js
> +        2000 + //20k SSTORE for a batch of 10 transctions
Actually *2661

2021-04-28 17:30 UTC, K-Ho commented on packages/optimism.io/src/components/GasCalcSection/index.js
> +        2000 + //20k SSTORE for a batch of 10 transctions
```
const l1GasUsed =
        zeroBytes * 4 +
        dataBytes * 16 +
        2661 // (tx batches of size 200)
const cost = l1GasUsed * l1GasPrice + executionPrice* l2GasUsed // executionPrice is 0 so we can ignore this second half
```

2021-04-30 18:38 UTC, gigamesh commented
@K-Ho updated the staging link but the math def needs your review

2021-05-05 20:22 UTC, K-Ho commented
I think we should add the L2gasPrice * l2ExecutionGas to the fee calculation even though L2GasPrice is currently 0
```
const layer2GasFee = layer1GasPrice * layer1Gas
// Layer 2 computation costs are currently not added to the fee, but will be in the future
```
should instead be 
```
const layer2GasFee = layer1GasPrice * layer1Gas + layer2GasPrice * layer2Gas
```

and in calculation it'll be 
```
const layer2GasFee = layer1GasPrice * layer1Gas + 0 * layer2Gas
```
We can estimate layer2Gas as being the l1gasUsed * 5 right now (tooltip could describe that there is an OVM execution overhead at the moment). and we can add a toolTip that layer2GasPrice will be 0 until the L2 chain becomes congested and is processing ~2.5x the amount of execution as L1 Ethereum

2021-05-05 20:22 UTC, K-Ho commented
other than that lgtm

2021-05-06 19:26 UTC, platocrat requested changes

2021-05-06 19:26 UTC, platocrat commented on packages/optimism.io/src/components/Navigation/index.js
> +// import { ExternalLinkIcon } from '@chakra-ui/icons';
are you going to use this line at some point?
Wondering why you pushed this commented line instead of removing or uncommenting it

2021-05-06 19:52 UTC, platocrat requested changes

2021-05-06 19:52 UTC, platocrat commented on packages/optimism.io/src/components/GasCalcSection/Formula.js
> +        <TTip label="The current price per gas on layer 1.">
I think this should read, `The current gas price for a single Gwei on layer 1`, since "price per gas" doesn't make sense.
Gas price is denominated in Gwei and I think the `layer2GasFee` formula is trying to multiply $USD by Gwei.
So, it would make sense that you have the price for 1 Gwei on the left, and the amount of layer 1 Gwei required to submit the tx on layer 2  on the right.

2021-05-06 20:03 UTC, platocrat requested changes

2021-05-06 20:03 UTC, platocrat commented on packages/optimism.io/src/components/GasCalcSection/index.js
> +                    className={
I really like the styling of these project logo styled-buttons.
The drop-shadow is great!
Although, I think the buttons would be more intuitive if the buttons were initialized to start at smaller size and only enlarge when clicked.
I think that enlarging-when-clicked centers the attention on the clicked icon rather than shrinking-when-clicked, which I think pushes the attention away towards the unclicked icon.

2021-05-06 20:05 UTC, platocrat commented
Suggested some minor changes, but besides that, it LGTM

2021-05-06 20:05 UTC, platocrat approved these changes

2021-05-06 20:36 UTC, gigamesh commented on packages/optimism.io/src/components/GasCalcSection/Formula.js
> +        <TTip label="The current price per gas on layer 1.">
gwei is the currrency though, so "price for a single Gwei" would be like saying "price for a single dollar"

I agree "price per gas" sounds weird but gas is computation, and its denomination is literally called "gas". This has confused me too. There are a lot of incorrect explanations of it floating around (ex: investopedia is a top google hit). Good one here: https://ethereum.org/en/developers/docs/gas/

Maybe "price per unit of gas" instead?

2021-05-06 21:01 UTC, gigamesh commented on packages/optimism.io/src/components/GasCalcSection/index.js
> +                    className={
done

2021-05-06 21:42 UTC, platocrat commented on packages/optimism.io/src/components/GasCalcSection/Formula.js
> +        <TTip label="The current price per gas on layer 1.">
Price per unit of gas is what I was looking for

2021-05-07 16:45 UTC, merged