Adds more details to status page
ethereum-optimism/frontends pull request #28
Opened 2021-04-23 01:04 UTC by gigamesh

![image](https://user-images.githubusercontent.com/32403632/115803145-26b85000-a395-11eb-93dc-d3c3a62ff6ce.png)

2021-04-23 01:51 UTC, snario commented
Seems like it's not working after a recent mainnet update:

![image](https://user-images.githubusercontent.com/1933029/115806483-b19c4900-a39b-11eb-8647-3ab190e8c75f.png)

https://etherscan.io/address/0xfd7d4de366850c08ee2cba32d851385a3071ec8d
![image](https://user-images.githubusercontent.com/1933029/115806498-b5c86680-a39b-11eb-889b-68f5459444a6.png)

2021-04-23 17:02 UTC, gigamesh commented
@snario 

I'm at a loss as to what was going on there. It seems to be working correctly now.

2021-04-23 17:08 UTC, gigamesh commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +            Number(totalElements.toString())
@K-Ho In the issue, you said to get the timestamp of the `totalElements + 1` (unsubmitted) block, but I think that might make this overly complicated since I need to show the user the time since the last _submitted_ block. Do you think this is sufficient?

2021-04-23 17:44 UTC, snario commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +        console.log(err);
We may want to hook up Sentry to this page to capture these sorts of issues.

2021-04-23 17:50 UTC, snario commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +      }
This entire block seems unnecessarily complicated to me... why isn't is as simple as querying [`CTC.getLastTimestamp`](https://etherscan.io/readContract?m=normal&a=0x405B4008Da75C48F4E54AA39607378967Ae62338&v=0x405B4008Da75C48F4E54AA39607378967Ae62338#readCollapse9) and comparing it to `Date.now()`?

2021-04-23 19:09 UTC, gigamesh commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +        console.log(err);
Do you think this is a near-term priority? I'm thinking I should mainly focus on refactoring the Gateway from The Graph to Etherscan at the moment.

2021-04-23 19:11 UTC, gigamesh commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +      }
Oh I didn't even realize that method existed. @K-Ho does that sound good to you?

2021-04-24 01:07 UTC, gigamesh commented
Worked correctly when kovan just went completely down (Mark confirmed it): 

![image](https://user-images.githubusercontent.com/32403632/115942355-bfff6900-a45e-11eb-8a83-04d70026c2ea.png)

2021-04-24 16:34 UTC, snario commented
Can we do "1 hour and 30 minutes ago" instead of "1.52 hours ago"?

2021-04-26 18:18 UTC, snario commented on packages/gateway.optimism.io/src/hooks/useWallet.tsx
> +  console.log(test);
👀

2021-04-26 21:21 UTC, snario requested changes

2021-04-26 21:21 UTC, snario commented on packages/common-ui/src/contracts/abis.js
> +import OVM_StateCommitmentChain from './abis/OVM_StateCommitmentChain.json';
You should be able to import from `@eth-optimism/contracts` no?

2021-04-26 21:21 UTC, snario commented on packages/gateway.optimism.io/src/hooks/useWallet.tsx
> +  console.log(test);
Should remove.

2021-04-26 21:21 UTC, snario commented on packages/optimism.io/src/components/NetworkCard/index.js
> +  if (intervalSinceLastBatch.count() > 86_400_000) {
Can you comment next to this with the number of hours this is?

2021-04-26 21:21 UTC, snario commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +const MAINNET_STC_ADDRESS = '0x1D0C46671E0696a4Ba800032D5195d5b0f8c60A3';
We should log an issue in the monorepo to export these values from `@eth-optimism/contracts` if we're not already. Actually, aren't we already?

2021-04-26 21:21 UTC, snario commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +          return Date.now() - lastTimestamp * 1000;
Is this right? Not `(Date.now() - lastTimestamp) * 1000;`

2021-04-26 22:56 UTC, gigamesh commented on packages/optimism.io/src/pages/NetworkStatus/index.js
> +          return Date.now() - lastTimestamp * 1000;
Yep - lastTimestamp is in seconds & the multiplication happens first

2021-04-27 16:33 UTC, gigamesh commented
@snario should I hold this PR until the `@ethereum-optimism/contracts` repo is updated? Otherwise I think its ready to go: 

https://60883a04e889560008c3e0c6--optimism-io.netlify.app/status

2021-04-27 19:11 UTC, snario commented
> @snario should I hold this PR until the `@ethereum-optimism/contracts` repo is updated? Otherwise I think its ready to go:
> 
> https://60883a04e889560008c3e0c6--optimism-io.netlify.app/status

Let's not block this PR from being merged, but let's still do the update in a new PR after?

2021-04-27 19:47 UTC, merged